### PR TITLE
Feature/spot rest v3 (Trading)

### PR DESCRIPTION
**Pull request by kulikov-dev**
For my tasks added supports of spot REST client for API v3 (now for Trading only). The main reason - stop limit orders.
If this approach is suitable for you - please keep me informed, will do the others: Exchange and Accounts.

### CODE REVIEW

**Comment by JKorf** [comment]
Hi @kulikov-dev , thanks for your work on this. I see you've created 4 pull requests, but I think each one is extending on the previous one? So this (currently) last PR contains all the changes the last also have?
It would be great if you could also add the ExchangeData and Account endpoints. I currently don't have much time myself, so it would be a big help.
Just a note, there is unit test failing on this branch ;)

**Comment by kulikov-dev** [comment]
@JKorf Thank you for your answer! Yes, you are right it's 4 connected pull requests. I decided to do this, so you can see why I did each other. If all of them are suitable for your repository - after merging this one I will close others PR. 

I will also add the ExchangeData and Account endpoints in a few days.
P.S. The unit test are failing because of lack of these endpoints, don't worry :) After finishing all endpoints I'll recheck all unit tests.

**Comment by kulikov-dev** [comment]
@JKorf  Morning. Just have finished with the ExchangeData and Account endpoints. So now we have full both versions for V1 and V3 Spot Rest.
This PR also contains splitting the Spot Socket for V1, V2 and V3.

**Comment by JKorf** [comment]
Thanks for the work. You'll need to resolve some conflicts unfortunately. I think it's mostly docs, so shouldn't be too much work. Also I was wondering why the DecimalJsonConverter is needed?

**Comment by kulikov-dev** [comment]
I will glad to resolve it, unfortunately I got the message "Only those with [write access] to this repository can merge pull requests.". 
I've already done rebase, but it didn't help..

Good point about DecimalJsonConverter, thank you. It should be obsollete now, eliminated it.

**Comment by kulikov-dev** [comment]
@JKorf Done.
Good point about DecimalJsonConverter, thank you. It should be obsollete now, eliminated it.

**Comment by JKorf** [comment]
Thanks, looks good!

**Pull request merged**
